<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class CompaniesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table("companies")->delete();

        DB::table("companies")->insert([
            [
                "id" => 1,
                "name" => "Company A Corp",
                "industry" => "Retail",
                "website" => "https://company1.com",
                "address" => "980 Business Rd, Suite 1",
                "logo_url" => null,
                "created_at" => "2026-01-31 05:21:36",
                "updated_at" => "2026-01-31 05:21:36",
            ],
            [
                "id" => 2,
                "name" => "Company B Corp",
                "industry" => "Retail",
                "website" => "https://company2.com",
                "address" => "502 Business Rd, Suite 2",
                "logo_url" => null,
                "created_at" => "2025-06-17 01:08:57",
                "updated_at" => "2025-06-17 01:08:57",
            ],
            [
                "id" => 3,
                "name" => "Company C Corp",
                "industry" => "Consulting",
                "website" => "https://company3.com",
                "address" => "334 Business Rd, Suite 3",
                "logo_url" => null,
                "created_at" => "2025-07-10 22:47:50",
                "updated_at" => "2025-07-10 22:47:50",
            ],
            [
                "id" => 4,
                "name" => "Company D Corp",
                "industry" => "Real Estate",
                "website" => "https://company4.com",
                "address" => "661 Business Rd, Suite 4",
                "logo_url" => null,
                "created_at" => "2025-04-23 18:01:14",
                "updated_at" => "2025-04-23 18:01:14",
            ],
            [
                "id" => 5,
                "name" => "Company E Corp",
                "industry" => "Consulting",
                "website" => "https://company5.com",
                "address" => "482 Business Rd, Suite 5",
                "logo_url" => null,
                "created_at" => "2025-05-17 01:26:22",
                "updated_at" => "2025-05-17 01:26:22",
            ],
            [
                "id" => 6,
                "name" => "Company F Corp",
                "industry" => "Healthcare",
                "website" => "https://company6.com",
                "address" => "250 Business Rd, Suite 6",
                "logo_url" => null,
                "created_at" => "2025-12-07 11:08:31",
                "updated_at" => "2025-12-07 11:08:31",
            ],
            [
                "id" => 7,
                "name" => "Company G Corp",
                "industry" => "Manufacturing",
                "website" => "https://company7.com",
                "address" => "350 Business Rd, Suite 7",
                "logo_url" => null,
                "created_at" => "2025-07-14 20:11:27",
                "updated_at" => "2025-07-14 20:11:27",
            ],
            [
                "id" => 8,
                "name" => "Company H Corp",
                "industry" => "Consulting",
                "website" => "https://company8.com",
                "address" => "196 Business Rd, Suite 8",
                "logo_url" => null,
                "created_at" => "2025-12-03 08:20:24",
                "updated_at" => "2025-12-03 08:20:24",
            ],
            [
                "id" => 9,
                "name" => "Company I Corp",
                "industry" => "Consulting",
                "website" => "https://company9.com",
                "address" => "943 Business Rd, Suite 9",
                "logo_url" => null,
                "created_at" => "2025-08-08 06:02:32",
                "updated_at" => "2025-08-08 06:02:32",
            ],
            [
                "id" => 10,
                "name" => "Company J Corp",
                "industry" => "Technology",
                "website" => "https://company10.com",
                "address" => "170 Business Rd, Suite 10",
                "logo_url" => null,
                "created_at" => "2025-09-12 22:52:29",
                "updated_at" => "2025-09-12 22:52:29",
            ],
            [
                "id" => 11,
                "name" => "Company K Corp",
                "industry" => "Technology",
                "website" => "https://company11.com",
                "address" => "851 Business Rd, Suite 11",
                "logo_url" => null,
                "created_at" => "2025-04-25 16:48:34",
                "updated_at" => "2025-04-25 16:48:34",
            ],
            [
                "id" => 12,
                "name" => "Company L Corp",
                "industry" => "Manufacturing",
                "website" => "https://company12.com",
                "address" => "795 Business Rd, Suite 12",
                "logo_url" => null,
                "created_at" => "2025-07-20 19:53:57",
                "updated_at" => "2025-07-20 19:53:57",
            ],
            [
                "id" => 13,
                "name" => "Company M Corp",
                "industry" => "Technology",
                "website" => "https://company13.com",
                "address" => "129 Business Rd, Suite 13",
                "logo_url" => null,
                "created_at" => "2025-07-15 23:48:52",
                "updated_at" => "2025-07-15 23:48:52",
            ],
            [
                "id" => 14,
                "name" => "Company N Corp",
                "industry" => "Finance",
                "website" => "https://company14.com",
                "address" => "996 Business Rd, Suite 14",
                "logo_url" => null,
                "created_at" => "2026-03-05 01:31:10",
                "updated_at" => "2026-03-05 01:31:10",
            ],
            [
                "id" => 15,
                "name" => "Company O Corp",
                "industry" => "Consulting",
                "website" => "https://company15.com",
                "address" => "862 Business Rd, Suite 15",
                "logo_url" => null,
                "created_at" => "2026-03-16 06:07:34",
                "updated_at" => "2026-03-16 06:07:34",
            ],
            [
                "id" => 16,
                "name" => "Company P Corp",
                "industry" => "Real Estate",
                "website" => "https://company16.com",
                "address" => "334 Business Rd, Suite 16",
                "logo_url" => null,
                "created_at" => "2025-06-02 05:07:13",
                "updated_at" => "2025-06-02 05:07:13",
            ],
            [
                "id" => 17,
                "name" => "Company Q Corp",
                "industry" => "Real Estate",
                "website" => "https://company17.com",
                "address" => "513 Business Rd, Suite 17",
                "logo_url" => null,
                "created_at" => "2025-09-18 13:35:47",
                "updated_at" => "2025-09-18 13:35:47",
            ],
            [
                "id" => 18,
                "name" => "Company R Corp",
                "industry" => "Manufacturing",
                "website" => "https://company18.com",
                "address" => "640 Business Rd, Suite 18",
                "logo_url" => null,
                "created_at" => "2025-10-12 19:21:35",
                "updated_at" => "2025-10-12 19:21:35",
            ],
            [
                "id" => 19,
                "name" => "Company S Corp",
                "industry" => "Real Estate",
                "website" => "https://company19.com",
                "address" => "826 Business Rd, Suite 19",
                "logo_url" => null,
                "created_at" => "2025-05-15 23:35:22",
                "updated_at" => "2025-05-15 23:35:22",
            ],
            [
                "id" => 20,
                "name" => "Company T Corp",
                "industry" => "Healthcare",
                "website" => "https://company20.com",
                "address" => "603 Business Rd, Suite 20",
                "logo_url" => null,
                "created_at" => "2026-01-01 13:05:42",
                "updated_at" => "2026-01-01 13:05:42",
            ],
            [
                "id" => 21,
                "name" => "Rassogolla Pvt. LTD.",
                "industry" => "Juicy",
                "website" => "https://souze-san.vercel.app",
                "address" => "123 business Road, Near Sonagachi",
                "logo_url" => null,
                "created_at" => "2026-03-21 05:49:28",
                "updated_at" => "2026-03-21 05:49:28",
            ],
        ]);
    }
}
