<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ContactsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table("contacts")->delete();

        DB::table("contacts")->insert([
            [
                "id" => 1,
                "first_name" => "Sarah",
                "last_name" => "Connor",
                "avatar" => "avatars/p2.jpg",
                "email" => "sarah@acme.com",
                "phone" => "555-0101",
                "job_title" => "CTO",
                "status" => "Customer",
                "company_id" => 1,
                "owner_id" => 1,
                "created_at" => "2025-04-12 10:00:00",
                "updated_at" => "2025-04-12 10:00:00",
            ],
            [
                "id" => 2,
                "first_name" => "John",
                "last_name" => "Smith",
                "avatar" => "avatars/p1.jpg",
                "email" => "john@gretail.com",
                "phone" => "555-0102",
                "job_title" => "VP Sales",
                "status" => "Customer",
                "company_id" => 2,
                "owner_id" => 1,
                "created_at" => "2025-05-18 09:30:00",
                "updated_at" => "2025-05-18 09:30:00",
            ],
            [
                "id" => 3,
                "first_name" => "Emma",
                "last_name" => "Watson",
                "avatar" => "avatars/p3.jpg",
                "email" => "emma@healthplus.org",
                "phone" => "555-0103",
                "job_title" => "Director",
                "status" => "Customer",
                "company_id" => 3,
                "owner_id" => 1,
                "created_at" => "2025-06-25 14:15:00",
                "updated_at" => "2025-06-25 14:15:00",
            ],
            [
                "id" => 4,
                "first_name" => "Michael",
                "last_name" => "Jordan",
                "avatar" => "avatars/p2.jpg",
                "email" => "mj@finserve.com",
                "phone" => "555-0104",
                "job_title" => "CEO",
                "status" => "Lead",
                "company_id" => 4,
                "owner_id" => 1,
                "created_at" => "2025-07-10 11:45:00",
                "updated_at" => "2025-07-10 11:45:00",
            ],
            [
                "id" => 5,
                "first_name" => "Olivia",
                "last_name" => "Pope",
                "avatar" => "avatars/p1.jpg",
                "email" => "olivia@buildright.com",
                "phone" => "555-0105",
                "job_title" => "Manager",
                "status" => "Competitor",
                "company_id" => 5,
                "owner_id" => 1,
                "created_at" => "2025-08-15 16:20:00",
                "updated_at" => "2025-08-15 16:20:00",
            ],
            [
                "id" => 6,
                "first_name" => "James",
                "last_name" => "Bond",
                "avatar" => "avatars/p3.jpg",
                "email" => "james@edutech.io",
                "phone" => "555-0106",
                "job_title" => "Agent",
                "status" => "Customer",
                "company_id" => 6,
                "owner_id" => 1,
                "created_at" => "2025-09-05 08:00:00",
                "updated_at" => "2025-09-05 08:00:00",
            ],
            [
                "id" => 7,
                "first_name" => "Bruce",
                "last_name" => "Wayne",
                "avatar" => "avatars/p2.jpg",
                "email" => "bruce@automakers.com",
                "phone" => "555-0107",
                "job_title" => "CEO",
                "status" => "Ex-Customer",
                "company_id" => 7,
                "owner_id" => 1,
                "created_at" => "2025-10-20 13:10:00",
                "updated_at" => "2025-10-20 13:10:00",
            ],
            [
                "id" => 8,
                "first_name" => "Clark",
                "last_name" => "Kent",
                "avatar" => "avatars/p1.jpg",
                "email" => "clark@consultpro.com",
                "phone" => "555-0108",
                "job_title" => "Consultant",
                "status" => "Lead",
                "company_id" => 8,
                "owner_id" => 1,
                "created_at" => "2025-11-25 09:50:00",
                "updated_at" => "2025-11-25 09:50:00",
            ],
            [
                "id" => 9,
                "first_name" => "Diana",
                "last_name" => "Prince",
                "avatar" => "avatars/p1.jpg",
                "email" => "diana@ecofoods.com",
                "phone" => "555-0109",
                "job_title" => "VP Marketing",
                "status" => "Customer",
                "company_id" => 9,
                "owner_id" => 1,
                "created_at" => "2025-12-10 15:30:00",
                "updated_at" => "2025-12-10 15:30:00",
            ],
            [
                "id" => 10,
                "first_name" => "Tony",
                "last_name" => "Stark",
                "avatar" => "avatars/p2.jpg",
                "email" => "tony@securenet.net",
                "phone" => "555-0110",
                "job_title" => "CEO",
                "status" => "Customer",
                "company_id" => 10,
                "owner_id" => 1,
                "created_at" => "2026-01-18 10:20:00",
                "updated_at" => "2026-01-18 10:20:00",
            ],
            [
                "id" => 11,
                "first_name" => "Steve",
                "last_name" => "Rogers",
                "avatar" => "avatars/p1.jpg",
                "email" => "steve@primelog.com",
                "phone" => "555-0111",
                "job_title" => "Ops Lead",
                "status" => "Competitor",
                "company_id" => 11,
                "owner_id" => 1,
                "created_at" => "2026-02-05 12:00:00",
                "updated_at" => "2026-02-05 12:00:00",
            ],
            [
                "id" => 12,
                "first_name" => "Natasha",
                "last_name" => "Romanoff",
                "avatar" => "avatars/p2.jpg",
                "email" => "nat@apexfin.com",
                "phone" => "555-0112",
                "job_title" => "Analyst",
                "status" => "Lead",
                "company_id" => 12,
                "owner_id" => 1,
                "created_at" => "2026-03-02 09:15:00",
                "updated_at" => "2026-03-02 09:15:00",
            ],
            [
                "id" => 13,
                "first_name" => "Clint",
                "last_name" => "Barton",
                "avatar" => "avatars/p1.jpg",
                "email" => "clint@carefirst.org",
                "phone" => "555-0113",
                "job_title" => "Specialist",
                "status" => "Customer",
                "company_id" => 13,
                "owner_id" => 1,
                "created_at" => "2026-03-08 14:40:00",
                "updated_at" => "2026-03-08 14:40:00",
            ],
            [
                "id" => 14,
                "first_name" => "Wanda",
                "last_name" => "Maximoff",
                "avatar" => "avatars/p2.jpg",
                "email" => "wanda@nextgenrealty.com",
                "phone" => "555-0114",
                "job_title" => "Agent",
                "status" => "Competitor",
                "company_id" => 14,
                "owner_id" => 1,
                "created_at" => "2026-03-12 11:10:00",
                "updated_at" => "2026-03-12 11:10:00",
            ],
            [
                "id" => 15,
                "first_name" => "Batabi",
                "last_name" => "Boudi",
                "avatar" => "avatars/p3.jpg",
                "email" => "batabi@crm.com",
                "phone" => "9823121212",
                "job_title" => "Marketing Head",
                "status" => "Customer",
                "company_id" => 15,
                "owner_id" => 1,
                "created_at" => "2026-03-21 05:49:28",
                "updated_at" => "2026-03-21 05:49:28",
            ],
            [
                "id" => 16,
                "first_name" => "Peter",
                "last_name" => "Parker",
                "avatar" => "avatars/p1.jpg",
                "email" => "peter@freelance.com",
                "phone" => "555-0116",
                "job_title" => "Photographer",
                "status" => "Lead",
                "company_id" => 10,
                "owner_id" => 1,
                "created_at" => "2025-06-12 10:10:00",
                "updated_at" => "2025-06-12 10:10:00",
            ],
            [
                "id" => 17,
                "first_name" => "Stephen",
                "last_name" => "Strange",
                "avatar" => "avatars/p2.jpg",
                "email" => "stephen@freelance.com",
                "phone" => "555-0117",
                "job_title" => "Doctor",
                "status" => "Ex-Customer",
                "company_id" => 12,
                "owner_id" => 1,
                "created_at" => "2025-08-22 11:11:00",
                "updated_at" => "2025-08-22 11:11:00",
            ],
            [
                "id" => 18,
                "first_name" => "Carol",
                "last_name" => "Danvers",
                "avatar" => "avatars/p3.jpg",
                "email" => "carol@freelance.com",
                "phone" => "555-0118",
                "job_title" => "Pilot",
                "status" => "Competitor",
                "company_id" => 1,
                "owner_id" => 1,
                "created_at" => "2025-11-05 12:12:00",
                "updated_at" => "2025-11-05 12:12:00",
            ],
            [
                "id" => 19,
                "first_name" => "Aura",
                "last_name" => "auraa",
                "avatar" => "avatars/p3.jpg",
                "email" => "aura@crm.com",
                "phone" => "0987654567",
                "job_title" => "Marketing Head",
                "status" => "Lead",
                "company_id" => 11,
                "owner_id" => 1,
                "created_at" => "2026-03-20 14:09:22",
                "updated_at" => "2026-03-20 14:09:22",
            ],
            [
                "id" => 20,
                "first_name" => "oreoo",
                "last_name" => "oreo",
                "avatar" => "avatars/p1.jpg",
                "email" => "oreo@crm.com",
                "phone" => "8752312334",
                "job_title" => "CEO",
                "status" => "Lead",
                "company_id" => 12,
                "owner_id" => 1,
                "created_at" => "2026-03-20 14:09:51",
                "updated_at" => "2026-03-20 14:09:51",
            ],
            [
                "id" => 21,
                "first_name" => "Bob",
                "last_name" => "Builder",
                "avatar" => "avatars/p2.jpg",
                "email" => "bob@builder.com",
                "phone" => "555-0121",
                "job_title" => "Foreman",
                "status" => "Customer",
                "company_id" => 5,
                "owner_id" => 1,
                "created_at" => "2026-03-04 03:14:10",
                "updated_at" => "2026-03-04 03:14:10",
            ],
            [
                "id" => 22,
                "first_name" => "Joshua",
                "last_name" => "Rodriguez",
                "avatar" => "avatars/p1.jpg",
                "email" => "contact22@example.com",
                "phone" => "512-195-4269",
                "job_title" => "Marketing Director",
                "status" => "Customer",
                "company_id" => 12,
                "owner_id" => 1,
                "created_at" => "2026-03-04 03:14:10",
                "updated_at" => "2026-03-04 03:14:10",
            ],
            [
                "id" => 23,
                "first_name" => "Melissa",
                "last_name" => "Garcia",
                "avatar" => "avatars/p1.jpg",
                "email" => "contact23@example.com",
                "phone" => "633-499-3046",
                "job_title" => "Marketing Director",
                "status" => "Customer",
                "company_id" => 18,
                "owner_id" => 1,
                "created_at" => "2025-12-14 05:55:16",
                "updated_at" => "2025-12-14 05:55:16",
            ],
            [
                "id" => 24,
                "first_name" => "Sarah",
                "last_name" => "Miller",
                "avatar" => null,
                "email" => "contact24@example.com",
                "phone" => "717-286-2931",
                "job_title" => "Sales Lead",
                "status" => "Lead",
                "company_id" => 2,
                "owner_id" => 1,
                "created_at" => "2025-11-11 04:16:02",
                "updated_at" => "2025-11-11 04:16:02",
            ],
            [
                "id" => 25,
                "first_name" => "Ashley",
                "last_name" => "Miller",
                "avatar" => "avatars/p2.jpg",
                "email" => "contact25@example.com",
                "phone" => "396-491-1676",
                "job_title" => "Marketing Director",
                "status" => "Lead",
                "company_id" => 11,
                "owner_id" => 1,
                "created_at" => "2025-11-25 17:39:14",
                "updated_at" => "2025-11-25 17:39:14",
            ],
            [
                "id" => 26,
                "first_name" => "Ashley",
                "last_name" => "Williams",
                "avatar" => "avatars/p3.jpg",
                "email" => "contact26@example.com",
                "phone" => "479-889-4845",
                "job_title" => "Project Manager",
                "status" => "Customer",
                "company_id" => 13,
                "owner_id" => 1,
                "created_at" => "2025-12-19 20:59:37",
                "updated_at" => "2025-12-19 20:59:37",
            ],
            [
                "id" => 27,
                "first_name" => "Jane",
                "last_name" => "Martinez",
                "avatar" => "avatars/p2.jpg",
                "email" => "contact27@example.com",
                "phone" => "888-912-3432",
                "job_title" => "Sales Lead",
                "status" => "Customer",
                "company_id" => 13,
                "owner_id" => 1,
                "created_at" => "2025-12-03 04:28:18",
                "updated_at" => "2025-12-03 04:28:18",
            ],
            [
                "id" => 28,
                "first_name" => "Matthew",
                "last_name" => "Johnson",
                "avatar" => "avatars/p1.jpg",
                "email" => "contact28@example.com",
                "phone" => "362-239-8697",
                "job_title" => "Sales Lead",
                "status" => "Customer",
                "company_id" => 4,
                "owner_id" => 1,
                "created_at" => "2025-10-08 10:53:27",
                "updated_at" => "2025-10-08 10:53:27",
            ],
            [
                "id" => 29,
                "first_name" => "Matthew",
                "last_name" => "Garcia",
                "avatar" => "avatars/p3.jpg",
                "email" => "contact29@example.com",
                "phone" => "873-990-2173",
                "job_title" => "CTO",
                "status" => "Lead",
                "company_id" => 2,
                "owner_id" => 1,
                "created_at" => "2025-09-30 01:07:00",
                "updated_at" => "2025-09-30 01:07:00",
            ],
            [
                "id" => 30,
                "first_name" => "Melissa",
                "last_name" => "Garcia",
                "avatar" => "avatars/p1.jpg",
                "email" => "contact30@example.com",
                "phone" => "814-959-4300",
                "job_title" => "Sales Lead",
                "status" => "Customer",
                "company_id" => 11,
                "owner_id" => 1,
                "created_at" => "2025-09-15 02:38:42",
                "updated_at" => "2025-09-15 02:38:42",
            ],
        ]);
    }
}
