<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class TasksTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table("tasks")->delete();

        DB::table("tasks")->insert([
            [
                "id" => 1,
                "title" => "Review contract terms",
                "due_date" => "2026-03-07",
                "status" => "Todo",
                "contact_id" => 17,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-03-01 17:48:28",
                "updated_at" => "2026-03-01 17:48:28",
            ],
            [
                "id" => 2,
                "title" => "Draft onboarding plan",
                "due_date" => "2026-01-29",
                "status" => "Complete",
                "contact_id" => 5,
                "user_id" => 1,
                "interaction_id" => 24,
                "created_at" => "2026-02-01 10:19:28",
                "updated_at" => "2026-02-01 10:19:28",
            ],
            [
                "id" => 3,
                "title" => "Send updated proposal",
                "due_date" => "2026-02-19",
                "status" => "In Progress",
                "contact_id" => 17,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-02-22 21:40:23",
                "updated_at" => "2026-02-22 21:40:23",
            ],
            [
                "id" => 4,
                "title" => "Send updated proposal",
                "due_date" => "2025-10-04",
                "status" => "Todo",
                "contact_id" => 20,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-10-13 11:35:02",
                "updated_at" => "2025-10-13 11:35:02",
            ],
            [
                "id" => 5,
                "title" => "Draft onboarding plan",
                "due_date" => "2025-07-05",
                "status" => "In Progress",
                "contact_id" => 12,
                "user_id" => 1,
                "interaction_id" => 32,
                "created_at" => "2025-06-25 21:46:24",
                "updated_at" => "2025-06-25 21:46:24",
            ],
            [
                "id" => 6,
                "title" => "Review contract terms",
                "due_date" => "2025-03-31",
                "status" => "Todo",
                "contact_id" => 18,
                "user_id" => 1,
                "interaction_id" => 33,
                "created_at" => "2025-03-24 16:20:07",
                "updated_at" => "2025-03-24 16:20:07",
            ],
            [
                "id" => 7,
                "title" => "Follow up call",
                "due_date" => "2025-12-25",
                "status" => "In Progress",
                "contact_id" => 22,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-12-31 07:17:48",
                "updated_at" => "2025-12-31 07:17:48",
            ],
            [
                "id" => 8,
                "title" => "Draft onboarding plan",
                "due_date" => "2026-01-05",
                "status" => "Complete",
                "contact_id" => 26,
                "user_id" => 1,
                "interaction_id" => 31,
                "created_at" => "2025-12-30 04:45:15",
                "updated_at" => "2025-12-30 04:45:15",
            ],
            [
                "id" => 9,
                "title" => "Prepare demo environment",
                "due_date" => "2025-06-06",
                "status" => "Todo",
                "contact_id" => 22,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-05-28 03:06:12",
                "updated_at" => "2025-05-28 03:06:12",
            ],
            [
                "id" => 10,
                "title" => "Draft onboarding plan",
                "due_date" => "2025-09-05",
                "status" => "In Progress",
                "contact_id" => 11,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-09-09 05:25:38",
                "updated_at" => "2025-09-09 05:25:38",
            ],
            [
                "id" => 11,
                "title" => "Draft onboarding plan",
                "due_date" => "2025-08-31",
                "status" => "Todo",
                "contact_id" => 30,
                "user_id" => 1,
                "interaction_id" => 37,
                "created_at" => "2025-08-21 22:47:56",
                "updated_at" => "2025-08-21 22:47:56",
            ],
            [
                "id" => 12,
                "title" => "Follow up call",
                "due_date" => "2025-05-28",
                "status" => "Todo",
                "contact_id" => 16,
                "user_id" => 1,
                "interaction_id" => 24,
                "created_at" => "2025-05-22 16:56:39",
                "updated_at" => "2025-05-22 16:56:39",
            ],
            [
                "id" => 13,
                "title" => "Prepare demo environment",
                "due_date" => "2026-02-28",
                "status" => "Complete",
                "contact_id" => 4,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-03-06 18:32:09",
                "updated_at" => "2026-03-06 18:32:09",
            ],
            [
                "id" => 14,
                "title" => "Prepare demo environment",
                "due_date" => "2025-06-09",
                "status" => "Todo",
                "contact_id" => 27,
                "user_id" => 1,
                "interaction_id" => 36,
                "created_at" => "2025-06-05 02:28:54",
                "updated_at" => "2025-06-05 02:28:54",
            ],
            [
                "id" => 15,
                "title" => "Review contract terms",
                "due_date" => "2026-03-09",
                "status" => "Complete",
                "contact_id" => 7,
                "user_id" => 1,
                "interaction_id" => 25,
                "created_at" => "2026-02-28 06:12:13",
                "updated_at" => "2026-02-28 06:12:13",
            ],
            [
                "id" => 16,
                "title" => "Draft onboarding plan",
                "due_date" => "2025-12-06",
                "status" => "Todo",
                "contact_id" => 10,
                "user_id" => 1,
                "interaction_id" => 4,
                "created_at" => "2025-12-05 08:12:23",
                "updated_at" => "2025-12-05 08:12:23",
            ],
            [
                "id" => 17,
                "title" => "Follow up call",
                "due_date" => "2026-02-10",
                "status" => "Todo",
                "contact_id" => 1,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-02-12 10:44:44",
                "updated_at" => "2026-02-12 10:44:44",
            ],
            [
                "id" => 18,
                "title" => "Send updated proposal",
                "due_date" => "2025-12-09",
                "status" => "Complete",
                "contact_id" => 20,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-11-29 22:37:58",
                "updated_at" => "2025-11-29 22:37:58",
            ],
            [
                "id" => 19,
                "title" => "Review contract terms",
                "due_date" => "2025-05-31",
                "status" => "In Progress",
                "contact_id" => 17,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-06-06 02:36:51",
                "updated_at" => "2025-06-06 02:36:51",
            ],
            [
                "id" => 20,
                "title" => "Send updated proposal",
                "due_date" => "2025-06-06",
                "status" => "In Progress",
                "contact_id" => 23,
                "user_id" => 1,
                "interaction_id" => 10,
                "created_at" => "2025-06-16 22:37:38",
                "updated_at" => "2025-06-16 22:37:38",
            ],
            [
                "id" => 21,
                "title" => "Follow up call",
                "due_date" => "2025-08-19",
                "status" => "Todo",
                "contact_id" => 15,
                "user_id" => 1,
                "interaction_id" => 24,
                "created_at" => "2025-08-09 13:36:39",
                "updated_at" => "2025-08-09 13:36:39",
            ],
            [
                "id" => 22,
                "title" => "Review contract terms",
                "due_date" => "2025-08-09",
                "status" => "In Progress",
                "contact_id" => 20,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-07-30 17:49:16",
                "updated_at" => "2025-07-30 17:49:16",
            ],
            [
                "id" => 23,
                "title" => "Draft onboarding plan",
                "due_date" => "2025-04-21",
                "status" => "Complete",
                "contact_id" => 29,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-04-30 06:41:06",
                "updated_at" => "2025-04-30 06:41:06",
            ],
            [
                "id" => 24,
                "title" => "Prepare demo environment",
                "due_date" => "2026-01-09",
                "status" => "Todo",
                "contact_id" => 8,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-01-11 19:38:59",
                "updated_at" => "2026-01-11 19:38:59",
            ],
            [
                "id" => 25,
                "title" => "Prepare demo environment",
                "due_date" => "2025-08-30",
                "status" => "Todo",
                "contact_id" => 21,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-09-09 19:28:57",
                "updated_at" => "2025-09-09 19:28:57",
            ],
            [
                "id" => 26,
                "title" => "Follow up call",
                "due_date" => "2025-05-19",
                "status" => "In Progress",
                "contact_id" => 27,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-05-21 18:47:24",
                "updated_at" => "2025-05-21 18:47:24",
            ],
            [
                "id" => 27,
                "title" => "Follow up call",
                "due_date" => "2025-05-25",
                "status" => "Todo",
                "contact_id" => 9,
                "user_id" => 1,
                "interaction_id" => 20,
                "created_at" => "2025-05-18 13:48:47",
                "updated_at" => "2025-05-18 13:48:47",
            ],
            [
                "id" => 28,
                "title" => "Send updated proposal",
                "due_date" => "2025-07-27",
                "status" => "In Progress",
                "contact_id" => 23,
                "user_id" => 1,
                "interaction_id" => 39,
                "created_at" => "2025-07-25 12:25:05",
                "updated_at" => "2025-07-25 12:25:05",
            ],
            [
                "id" => 29,
                "title" => "Send updated proposal",
                "due_date" => "2025-12-28",
                "status" => "Todo",
                "contact_id" => 19,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-01-04 06:29:54",
                "updated_at" => "2026-01-04 06:29:54",
            ],
            [
                "id" => 30,
                "title" => "Follow up call",
                "due_date" => "2026-02-02",
                "status" => "Complete",
                "contact_id" => 30,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-02-11 22:35:25",
                "updated_at" => "2026-02-11 22:35:25",
            ],
            [
                "id" => 31,
                "title" => "Prepare demo environment",
                "due_date" => "2025-08-09",
                "status" => "Todo",
                "contact_id" => 15,
                "user_id" => 1,
                "interaction_id" => 11,
                "created_at" => "2025-07-30 13:24:25",
                "updated_at" => "2025-07-30 13:24:25",
            ],
            [
                "id" => 32,
                "title" => "Prepare demo environment",
                "due_date" => "2026-03-18",
                "status" => "Complete",
                "contact_id" => 5,
                "user_id" => 1,
                "interaction_id" => 17,
                "created_at" => "2026-03-19 23:53:24",
                "updated_at" => "2026-03-19 23:53:24",
            ],
            [
                "id" => 33,
                "title" => "Send updated proposal",
                "due_date" => "2026-01-25",
                "status" => "Todo",
                "contact_id" => 6,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-01-24 01:24:20",
                "updated_at" => "2026-01-24 01:24:20",
            ],
            [
                "id" => 34,
                "title" => "Send updated proposal",
                "due_date" => "2025-08-07",
                "status" => "In Progress",
                "contact_id" => 30,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-08-14 02:55:48",
                "updated_at" => "2025-08-14 02:55:48",
            ],
            [
                "id" => 35,
                "title" => "Send updated proposal",
                "due_date" => "2026-02-15",
                "status" => "Todo",
                "contact_id" => 16,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2026-02-07 13:59:27",
                "updated_at" => "2026-02-07 13:59:27",
            ],
            [
                "id" => 36,
                "title" => "Follow up call",
                "due_date" => "2025-07-03",
                "status" => "In Progress",
                "contact_id" => 28,
                "user_id" => 1,
                "interaction_id" => 18,
                "created_at" => "2025-06-26 21:57:30",
                "updated_at" => "2025-06-26 21:57:30",
            ],
            [
                "id" => 37,
                "title" => "Send updated proposal",
                "due_date" => "2025-10-09",
                "status" => "Todo",
                "contact_id" => 8,
                "user_id" => 1,
                "interaction_id" => 35,
                "created_at" => "2025-10-07 06:03:32",
                "updated_at" => "2025-10-07 06:03:32",
            ],
            [
                "id" => 38,
                "title" => "Prepare demo environment",
                "due_date" => "2025-10-30",
                "status" => "In Progress",
                "contact_id" => 13,
                "user_id" => 1,
                "interaction_id" => 31,
                "created_at" => "2025-11-08 07:58:04",
                "updated_at" => "2025-11-08 07:58:04",
            ],
            [
                "id" => 39,
                "title" => "Follow up call",
                "due_date" => "2025-04-01",
                "status" => "Complete",
                "contact_id" => 12,
                "user_id" => 1,
                "interaction_id" => 32,
                "created_at" => "2025-04-11 12:44:09",
                "updated_at" => "2025-04-11 12:44:09",
            ],
            [
                "id" => 40,
                "title" => "Follow up call",
                "due_date" => "2025-12-29",
                "status" => "In Progress",
                "contact_id" => 2,
                "user_id" => 1,
                "interaction_id" => null,
                "created_at" => "2025-12-28 04:38:19",
                "updated_at" => "2025-12-28 04:38:19",
            ],
        ]);
    }
}
